const mongoose = require('mongoose');

const tripSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  destination: { type: String, required: true },
  durationDays: { type: Number, required: true },
  budgetLevel: { type: String, enum: ['Low', 'Medium', 'High'], required: true },
  interests: [{ type: String }],
  
  // Data generated by AI
  itinerary: [{
    day: Number,
    theme: String,
    activities: [{
      time: String,
      title: String,
      description: String,
      costEstimate: Number
    }]
  }],
  budgetBreakdown: {
    totalEstimated: Number,
    categories: [{ name: String, amount: Number }]
  },
  hotels: [{
    name: String,
    rating: Number,
    description: String,
    pricePerNight: Number
  }],
  smartPackingList: [{
    item: String,
    reason: String,
    packed: { type: Boolean, default: false }
  }],
  
  createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Trip', tripSchema);
